spring:
  application:
    name: dualis-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dualis_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:12345678}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: false
    locations: classpath:db/migration
